name: Update Driver of the Day Data

on:
  schedule:
    # Run every Monday at 12:00 UTC
    - cron: '59 23 26 10 *'
  workflow_dispatch:
    # Allow manual triggering

jobs:
  update-dotd-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run DOTD data fetcher
        run: |
          python latest_dotd.py

      - name: Check for changes
        id: git-check
        run: |
          git status --porcelain
          echo "changes=$(git status --porcelain | wc -l)" >> $GITHUB_OUTPUT

      - name: Commit and push if there are changes
        if: steps.git-check.outputs.changes > 0
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Update Driver of the Day data [automated]"
          git push
